
scraping:
  headless: False
  wait_seconds: 3
  request_delay_seconds: 2
  
  output_directory: "data/raw/fbref/matchlogs"
  file_format: "csv"   


players:
  # - player_id: "2f965a72"
  #   player_slug: "Alphonse-Areola"
  #   seasons:
  #     - "2025-2026"

  - player_id: "7a2e46a8"
    player_slug: "Alisson"
    seasons:
      - "2025-2026"
