
scraping:
  headless: False
  wait_seconds: 3
  request_delay_seconds: 2
  output_data_format: "csv"

discovery:
  base_url: "https://fbref.com/en/comps/9/keepers/Premier-League-Stats"
  seasons:
    - "2025-2026"  

output:
  public_dir: "public"
  matchlogs_dir: "data/raw/fbref/matchlogs"
  file_format: "csv"
